# base image
FROM node:16-alpine

# create & set working directory
RUN mkdir -p /usr/app
WORKDIR /usr/app

# copy source files
COPY components ./components
COPY hooks ./hooks
COPY src ./src
COPY public ./public
COPY next.config.js ./next.config.js
COPY jsconfig.json ./jsconfig.json
COPY package.json ./package.json
COPY pnpm-lock.yaml ./pnpm-lock.yaml

# install dependencies
RUN pnpm install

# start app
RUN npm run build
EXPOSE 3000

RUN apk add bash

COPY entrypoint.sh /tmp/entrypoint.sh
RUN chmod a+x /tmp/entrypoint.sh

CMD ["/tmp/entrypoint.sh"]
